name        : libgeocode-glib
version     : 3.16.2
release     : 4
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/geocode-glib/3.16/geocode-glib-3.16.2.tar.xz : a551ffdbd793d54a14e709c9d02e82dde3abc14eed8065abad92275a43fe2c97
license     : GPL-2.0+
summary     : Geocoding library
builddeps   :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
description : |
    geocode-glib is a convenience library for the geocoding (finding longitude,
    and latitude from an address) and reverse geocoding (finding an address from
    coordinates). It uses Nominatim service to achieve that. It also caches
    (reverse-)geocoding requests for faster results and to avoid unnecessary server
    load.    
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
