name       : libgeocode-glib
version    : 3.26.2
release    : 13
source     :
    - https://download.gnome.org/sources/geocode-glib/3.26/geocode-glib-3.26.2.tar.xz : 01fe84cfa0be50c6e401147a2bc5e2f1574326e2293b55c69879be3e82030fd1
license    : GPL-2.0-or-later
component  : desktop.gnome.core
summary    : Geocoding library
description: |
    geocode-glib is a convenience library for the geocoding (finding longitude, and latitude from an address) and reverse geocoding (finding an address fromcoordinates). It uses Nominatim service to achieve that. It also caches (reverse-)geocoding requests for faster results and to avoid unnecessary server load.
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - gtk-doc
setup      : |
    %meson_configure -Denable-installed-tests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
