name       : libgeocode-glib
version    : 3.26.0
release    : 8
source     :
    - https://download.gnome.org/sources/geocode-glib/3.26/geocode-glib-3.26.0.tar.xz : ea4086b127050250c158beff28dbcdf81a797b3938bb79bbaaecc75e746fbeee
license    : GPL-2.0-or-later
component  : desktop.gnome.core
summary    : Geocoding library
description: |
    geocode-glib is a convenience library for the geocoding (finding longitude, and latitude from an address) and reverse geocoding (finding an address fromcoordinates). It uses Nominatim service to achieve that. It also caches (reverse-)geocoding requests for faster results and to avoid unnecessary server load.
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - gtk-doc
setup      : |
    %meson_configure -Denable-installed-tests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
